[env]
API_URL = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
compatibility_date = "2024-04-13"

name = "dingyueqi"
type = "javascript"
account_id = "${{ secrets.ACCOUNT_ID }}"
workers_dev = true

[env.production]
zone_id = "${{ secrets.ZONE_ID }}"
route = "${{ secrets.ROUTE }}"

# [vars]
# UUID = ${{  secrets.UUID }}
# PATH = ${{  secrets.PATH }}
# HOST = ${{  secrets.HOST }}
# TOKEN = ${{  secrets.TOKEN }}
# ADDAPI = ${{  secrets.ADDAPI }}
# ADDCSV = ${{  secrets.ADDCSV }}
# ADD = ${{  secrets.ADD }}
