[env]
API_URL = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
main = "_worker.js"

name = "${{ secrets.SCRIPT_NAME }}"
type = "javascript"
account_id = "${{ secrets.ACCOUNT_ID }}"
workers_dev = true

[env.production]
zone_id = "${{ secrets.ZONE_ID }}"
route = "${{ secrets.route }}"

[vars]
UUID = "${{ secrets.UUID }}"
PATH = "${{ secrets.PATH }}"
HOST = "${{ secrets.HOST }}"
TOKEN = "${{ secrets.TOKEN }}"
ADDAPI = "${{ secrets.ADDAPI }}"
ADDCSV = "${{ secrets.ADDCSV }}"
ADD = "${{ secrets.ADD }}"
