name: buildAndDeployWorker

on:
  push:
    branches:
      - lxg20082008-patch-1
  workflow_dispatch: # 手动触发
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # 默认分支
    
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      # 解决secrets多行文本的问题
      - name: Set ADDAPI output
        id: set_ADDAPI
        run: |
          echo 'ADDAPI<<EOF' >> $GITHUB_ENV
          echo "${{ secrets.ADDAPI }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set ADDCSV output
        id: set_ADDCSV
        run: |
          echo 'ADDCSV<<EOF' >> $GITHUB_ENV
          echo "${{ secrets.ADDCSV }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set ADD output
        id: set_ADD
        run: |
          echo 'ADD<<EOF' >> $GITHUB_ENV
          echo "${{ secrets.ADD }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} --var UUID:"${{ secrets.UUID }}" PATH:"${{ secrets.PATH }}" HOST:"${{ secrets.HOST }}" TOKEN:"${{ secrets.TOKEN }}" ADDAPI:"${{ env.ADDAPI }}" ADDCSV:"${{ env.ADDCSV }}" ADD:"${{ env.ADD }}" # --compatibility-date ${{ steps.set_date.outputs.date }}
