name: buildAndDeployWorker

on:
  push:
    branches:
      - lxg20082008-patch-1
  workflow_dispatch: # 手动触发
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # 默认分支
    
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      # 解决secrets多行文本的问题
      - name: Prepare environment variables
        run: |
          ADDAPI_CONTENT=$(echo "${{ secrets.ADDAPI }}" | sed 's/^ */::add-mask::/' | sed ':a;N;$!ba;s/\n/\\n/g')
          ADDCSV_CONTENT=$(echo "${{ secrets.ADDCSV }}" | sed 's/^ */::add-mask::/' | sed ':a;N;$!ba;s/\n/\\n/g')
          ADD_CONTENT=$(echo "${{ secrets.ADD }}" | sed 's/^ */::add-mask::/' | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "ADDAPI_CONTENT=$ADDAPI_CONTENT" >> $GITHUB_ENV
          echo "ADDCSV_CONTENT=$ADDCSV_CONTENT" >> $GITHUB_ENV
          echo "ADD_CONTENT=$ADD_CONTENT" >> $GITHUB_ENV

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} --var UUID:"${{ secrets.UUID }}" PATH:"${{ secrets.PATH }}" HOST:"${{ secrets.HOST }}" TOKEN:"${{ secrets.TOKEN }}" ADDAPI_CONTENT:"${{ env.ADDAPI_CONTENT }}" ADDCSV_CONTENT:"${{ env.ADDCSV_CONTENT }}" ADD_CONTENT:"${{ env.ADD_CONTENT }}"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} --var UUID:"${{ secrets.UUID }}" PATH:"${{ secrets.PATH }}" HOST:"${{ secrets.HOST }}" TOKEN:"${{ secrets.TOKEN }}" ADDAPI:"${{ env.ADDAPI }}" ADDCSV:"${{ env.ADDCSV }}" ADD:"${{ env.ADD }}" # --compatibility-date ${{ steps.set_date.outputs.date }}
