name: buildAndDeployWorker
on:
  push:
    branches:
      - lxg20082008-patch-1
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.
  workflow_dispatch: # 手动触发
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # 默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Set Script Executable
        run: |
          chmod +x rewrite_secrets.sh

      - name: Rewrite Secrets
        run: |
          bash rewrite_secrets.sh

      - name: view temp_toml_file
        run: |
          cat "${{env.temp_toml_file}}"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --config "${{env.temp_toml_file}}" --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} # --compatibility-date ${{ steps.set_date.outputs.date }}

      - name: Remove Temporary File
        run: |
          rm "${{env.temp_toml_file}}"
