name: buildAndDeployWorker

on:
  push:
    branches:
      - lxg20082008-patch-1
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.
  workflow_dispatch: # Manual trigger
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # Default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4  # Fetch code from repository

      - name: Set Secrets
        run: |
          if [[ -n "${{ secrets.UUID }}" ]]; then
            echo "UUID=\"${{ secrets.UUID }}\" >> wrangler.toml"
          fi
          if [[ -n "${{ secrets.PATH }}" ]]; then
            echo "PATH=\"${{ secrets.PATH }}\" >> wrangler.toml"
          fi
          if [[ -n "${{ secrets.HOST }}" ]]; then
            echo "HOST=${{ secrets.HOST }}\\" >> wrangler.toml
          fi
          if [[ -n "${{ secrets.TOKEN }}" ]]; then
            echo "TOKEN=${{ secrets.TOKEN }}\\" >> wrangler.toml
          fi
          if [[ -n "${{ secrets.ADDAPI }}" ]]; then
            echo "ADDAPI=${{ secrets.ADDAPI }}\\" >> wrangler.toml
          fi
          if [[ -n "${{ secrets.ADDCSV }}" ]]; then
            echo "ADDCSV=${{ secrets.ADDCSV }}\\" >> wrangler.toml
          fi
          if [[ -n "${{ secrets.ADD }}" ]]; then
            echo "ADD=${{ secrets.ADD }}\" >> wrangler.toml
          fi
    
      - name: Show wrangler.toml contents (Optional)
        run: cat wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} # --compatibility-date ${{ steps.set_date.outputs.date }}
