name: buildAndDeployWorker

on:
  push:
    branches:
      - lxg20082008-patch-1
  # workflow_dispatch: # 手动触发
  #   inputs:
  #     logLevel:
  #       description: 'Log level'
  #       required: true
  #       default: 'warning'
  #       type: choice
  #       options:
  #       - info
  #       - warning
  #       - debug
  #     tags:
  #       description: 'Test scenario tags'
  #       required: false
  #       type: boolean
  #     environment:
  #       description: 'Environment to run tests against'
  #       type: environment
  #       required: true
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # 默认分支
    
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.

jobs:
  # log-the-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "Log level: $LEVEL"
  #         echo "Tags: $TAGS"
  #         echo "Environment: $ENVIRONMENT"
  #       env:
  #         LEVEL: ${{ inputs.logLevel }}
  #         TAGS: ${{ inputs.tags }}
  #         ENVIRONMENT: ${{ inputs.environment }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      # - name: Set Compatibility Date
      #   id: set_date
      #   run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      # # Debugging step to print out the environment variables
      # - name: Debug Environment Variables
      #   run: |
      #     echo "ADDAPI: $ADDAPI"
      #     echo "ADDCSV: $ADDCSV"
      #     echo "ADD: $ADD"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.script_name }} --var UUID:"${{ secrets.UUID }}" PATH:"${{ secrets.PATH }}" HOST:"${{ secrets.HOST }}" TOKEN:"${{ secrets.TOKEN }}" ADDAPI:"${{ secrets.ADDAPI }}" ADDCSV:"${{ secrets.ADDCSV }}" ADD:"${{ secrets.ADD }}" # --compatibility-date ${{ steps.set_date.outputs.date }}
