name: buildAndDeployWorker

on:
  push:
    branches:
      - lxg20082008-patch-1
  schedule:
    - cron: "0 05 * * 1,3,5,0" #At 05:00 on Monday, Wednesday, Friday, and Sunday.
  workflow_dispatch: # Manual trigger
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'lxg20082008-patch-1' # Default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4  # Fetch code from repository

      - name: Set Secrets
        run: |
          if [[ -z "${{ secrets.UUID }}" ]]; then
            # Do nothing (since the secret is empty)
          else
            echo "UUID=\"${{ secrets.UUID }}\" >> wrangler.toml"
          fi

          echo "PATH=\"${{ secrets.PATH }}\" >> wrangler.toml"
          echo "HOST=${{ secrets.HOST }}" >> wrangler.toml
          echo "TOKEN=${{ secrets.TOKEN }}" >> wrangler.toml
          echo "ADDAPI=${{ secrets.ADDAPI }}" >> wrangler.toml
          echo "ADDCSV=${{ secrets.ADDCSV }}" >> wrangler.toml
          echo "ADD=${{ secrets.ADD }}" >> wrangler.toml
    
      - name: Show wrangler.toml contents (Optional)
        run: cat wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: .
          command: deploy _worker.js --compatibility-date 2024-04-13 --name ${{ secrets.SCRIPT_NAME }} # --compatibility-date ${{ steps.set_date.outputs.date }}
