name: buildAndDeployWorker
on: push
  schedule:
    - cron: '00 5 * * 1,3,5,0' # 每天的上午5点0分触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
