- name: Deploy
  id: deploy
  uses: cloudflare/wrangler-action@v3
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    command: pages deploy --project-name=example

- name: print wrangler command output
  env:
    CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
  run: echo $CMD_OUTPUT
